version: '1.0'
name: branch-pipeline
displayName: BranchPipeline
stages:
  - stage:
    name: test
    displayName: 测试
    steps:
      - step: build@python
        name: test_python
        displayName: Python 测试
        pythonVersion: '3.9'
        commands:
          - python3 -m pip install --upgrade pip
          - pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
          - pip3 install uv
          - uv --version
          - uv lock
          - uv sync
          - uv run pytest || echo "No tests found, skipping"

  - stage:
    name: build
    displayName: 构建
    steps:
      - step: build@python
        name: build_python
        displayName: Python 构建
        pythonVersion: '3.9'
        artifacts:
          - name: PYTHON_DIST
            path:
              - dist/
        commands:
          - python3 -m pip install --upgrade pip
          - pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
          - pip3 install build uv
          - uv lock
          - uv sync
          - python3 -m build

      - step: build@nodejs
        name: build_webapp
        displayName: Webapp 构建
        nodeVersion: '20'
        artifacts:
          - name: WEBAPP_DIST
            path:
              - webapp/.next/
              - webapp/out/
        commands:
          - cd webapp
          - npm config set registry https://registry.npmmirror.com
          - npm install
          - npm run build

  - stage:
    name: package
    displayName: 打包
    steps:
      - step: publish@general_artifacts
        name: publish_backend
        displayName: 上传后端制品
        dependArtifact: PYTHON_DIST
        artifactName: backend-dev
        dependsOn: build_python

      - step: publish@general_artifacts
        name: publish_frontend
        displayName: 上传前端制品
        dependArtifact: WEBAPP_DIST
        artifactName: frontend-dev
        dependsOn: build_webapp

triggers:
  push:
    branches:
      exclude:
        - master
        - main
      include:
        - .*
